#!/bin/sh
rsync -av ./ sabrosso@caredev.sabrosso.online:~/caredev.sabrosso.online/careconcept --include=public/build  --include=public/.htaccess
--include=vendor --exclude-from=.gitignore --exclude=".*"